version: 2.1

jobs:
  publish:
    working_directory: ~/homebrew-taps
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Pull releases and patch formula
          command: go run publish.go
      - run:
          name: Commit changes
          command: |
            git add -A
            git commit -m "Patch qlik-cli release"
            git push
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - run:
          name: Dummy Test
          command: echo "It worked!"
  trigger:
    docker:
      - image: circleci/golang:1.14
    steps:
      - run:
          name: Trigger Job
          command: |
            echo "Triggering other job"
            curl --fail -u ${CCI_TOKEN} \
              -d build_parameters[CIRCLE_JOB]=test \
              https://circleci.com/api/v1.1/project/github/qlik-oss/homebrew-taps/tree/publish-experiments
workflows:
  dummy:
    jobs:
      - foo:
          filters:
            tags:
              only:
                - /v.*/
