# This file was generated by GoReleaser. DO NOT EDIT.
class QlikCorectl < Formula
  desc "corectl is a CLI tool for using Qlik Associative Engine."
  homepage "https://github.com/qlik-oss/corectl"
  version "1.4.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/qlik-oss/corectl/releases/download/v1.4.1/corectl-Darwin-x86_64.tar.gz"
    sha256 "1c4573cb89dbedae0b70ae86bfa1328bbb6b576d723fe1fee8fa6cb9221b0611"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/qlik-oss/corectl/releases/download/v1.4.1/corectl-Linux-x86_64.tar.gz"
      sha256 "fca420f3bbc1c80a342666a8e09743465d6ff0a12532b4720b59b76d7ecbdefd"
    end
  end

  def install
    bin.install "corectl"
  end

  test do
    assert_equal "corectl version: #{version}", shell_output("#{bin}/corectl version").chomp
  end
end
