# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QlikCli < Formula
  desc "qlik-cli is a Command Line Interface for Qlik Cloud."
  homepage ""
  version "2.22.0"

  on_macos do
    url "https://github.com/qlik-trial/qlik-cli/releases/download/v2.22.0/qlik-Darwin-x86_64.tar.gz"
    sha256 "ea5ee2e392b7aa36c764e004f52618f8c9c660f5490e398867f50caa038dbb39"

    def install
      bin.install "qlik"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the QlikCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/qlik-trial/qlik-cli/releases/download/v2.22.0/qlik-Linux-x86_64.tar.gz"
      sha256 "7fe9dcefb905f0ba2f4e8848077376b0fa4cb9fdf07c5042d878aaf8e14bcb2b"

      def install
        bin.install "qlik"
      end
    end
  end

  test do
    assert_equal "qlik version: #{version}", shell_output("#{bin}/qlik version").chomp
  end
end
