# This file was generated by GoReleaser. DO NOT EDIT.
class QlikCorectl < Formula
  desc "corectl is a CLI tool for using Qlik Associative Engine."
  homepage "https://github.com/qlik-oss/corectl"
  version "1.5.2"

  if OS.mac?
    url "https://github.com/qlik-oss/corectl/releases/download/v1.5.2/corectl-Darwin-x86_64.tar.gz"
    sha256 "8e4e099854e4fdee44de4bf17aa1636898d2bcaab735cac9659bb2ac5ec71537"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/qlik-oss/corectl/releases/download/v1.5.2/corectl-Linux-x86_64.tar.gz"
      sha256 "789473ed60bdd09f7d3c8b4dcdd7751893cc69318e027be375af84d030d16129"
    end
  end

  def install
    bin.install "corectl"
  end

  test do
    assert_equal "corectl version: #{version}", shell_output("#{bin}/corectl version").chomp
  end
end
