# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QlikCli < Formula
  desc "qlik-cli is a Command Line Interface for Qlik Cloud."
  version "2.21.0"

  on_macos do
    url "https://raw.githubusercontent.com/qlik-oss/homebrew-taps/master/bin/qlik-cli/v2.21.0/qlik-Darwin-x86_64.tar.gz"
    sha256 "1458bc8347de5c6883c579a2ee58ca71f7fe60c494c14e15347002062181c48a"

    def install
      bin.install "qlik"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the QlikCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/qlik-oss/homebrew-taps/master/bin/qlik-cli/v2.21.0/qlik-Linux-x86_64.tar.gz"
      sha256 "385226f9f69c14a31a9bc46cc8128445346f72596b5d652048cc1557fe3354fc"

      def install
        bin.install "qlik"
      end
    end
  end

  test do
    assert_equal "qlik version: #{version}", shell_output("#{bin}/qlik version").chomp
  end
end
