# This file was generated by GoReleaser. DO NOT EDIT.
class QlikCorectl < Formula
  desc "corectl is a CLI tool for using Qlik Associative Engine."
  homepage "https://github.com/qlik-oss/corectl"
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/qlik-oss/corectl/releases/download/v1.4.0/corectl-Darwin-x86_64.tar.gz"
    sha256 "5fe586b979cb169d3e78b0b6b82e11c0ccf0caf61e1778e1361ed1902a440619"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/qlik-oss/corectl/releases/download/v1.4.0/corectl-Linux-x86_64.tar.gz"
      sha256 "d05bcbe066ba435a7edef65ac4108c1781f9436b51a8b03fe7dbf49ab54ea998"
    end
  end

  def install
    bin.install "corectl"
  end

  test do
    assert_equal "corectl version: #{version}", shell_output("#{bin}/corectl version").chomp
  end
end
