# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QlikCli < Formula
  desc "qlik-cli is a Command Line Interface for Qlik Cloud."
  homepage ""
  version "2.20.3"

  on_macos do
    url "https://github.com/qlik-trial/qlik-cli/releases/download/v2.20.3/qlik-Darwin-x86_64.tar.gz"
    sha256 "59a5ba6082f2600d792dcf3bbdcfe9a040f1037b628acdbbb27add2c068550df"

    def install
      bin.install "qlik"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the QlikCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/qlik-trial/qlik-cli/releases/download/v2.20.3/qlik-Linux-x86_64.tar.gz"
      sha256 "7415e5b638303473998809fa8d244e781bfb5da5f276e8e33768c5b4ed897b78"

      def install
        bin.install "qlik"
      end
    end
  end

  test do
    assert_equal "qlik version: #{version}", shell_output("#{bin}/qlik version").chomp
  end
end
